### ISSUE TITLE
对于通知的分类

### ISSUE THREAD

**Issue by wynfrith** [wynfrith/taolijie#10]
用户接收到的消息应该分为多种

- 管理员通知
- 认证学生通知
- 商户通知

**Comment by wanghongfei** [comment]
她回学校了，以后随时过来吧！

**Comment by wynfrith** [comment]
恩,明天跨文化交流你也过来吧,要讲ppt~~

2015-03-08 22:17 GMT+08:00 王鸿飞 <notifications@github.com>:
