### ISSUE TITLE
用户表需要添加一个创建时间字段

### ISSUE THREAD

**Issue by wynfrith** [wynfrith/taolijie#12]

**Comment by wanghongfei** [comment]
查找所有二手，所有兼职，所有简历都加上了

**Comment by wynfrith** [comment]
获取所有的兼职方法没法找到相关的分类,可以重写一个查询分类的方法(最好是在Dto类上再加一个categoryName字段,这样不用二次查询分类).

**Comment by wanghongfei** [comment]
`JobPostDto`有一个`categoryId`字段，可以暂时先用这个查询分类。
