### ISSUE TITLE
数据库还有许多字段需要添加

### ISSUE THREAD

**Issue by wynfrith** [wynfrith/taolijie#15]
job表
- 工作时间字段(workTime)
- 工资单位 
- 公司名称

job分类表
- 分类的主题色 (color)

member表
- 创建时间
- 是否删除(封号)

resume表
- 发布时间

**Comment by wynfrith** [comment]
前期设计数据库时间应该长一点,到后面改太麻烦了 :(

**Comment by wanghongfei** [comment]
只要不修改各个表之间的关联关系，改起来还是不复杂的。我今天就把这些字段加上。

其实刚开始是因为需求不明确啊，具体细节上还需要哪此功能我们都没想出来，应该跟那个哥们商量才对。

**Comment by wanghongfei** [comment]
少的字段你就先在controller中写死，先跑起来，我加上之后再换上真实的数据
