### ISSUE TITLE
继续完善数据库

### ISSUE THREAD

**Issue by wynfrith** [wynfrith/taolijie#16]
member表
 个人总计投诉数 [**implemented**]

job表
 投诉数 [**implemented**]
 工作时间:text类型 [**implemented**]
 发布商家 [**DTO对象里有memberId, 根据memberId找到用户即可**]
 工资单位 (天,周,月) [**implemented**]

 
sh表
 投诉数 [**implemented**]

各种分类表
 主题色 [**implemented**]

评论表
 评论可以接回复 [**implemented**]

能想到的就这么多了

**Comment by wynfrith** [comment]
还有,要实现一个收藏的功能. 考虑添加收藏表或者是在member表中添加一些字段记录收藏的类别和id @wanghongfei

**Comment by wynfrith** [comment]
简历 二手 兼职 访问量统计

**Comment by wynfrith** [comment]
逆序输出列表

**Comment by wanghongfei** [comment]
收藏是收藏什么？ @wynfrith 
逆序输出列表, 是什么列表，按照什么排序

**Comment by wynfrith** [comment]
## 数据库部分补充:

### 1.resume表
-  phone_path字段 (用户图片路径)  是不是名字起错了?
- 简历需要记录浏览量 (二手和兼职也需要)
- 简历要实现可以用户手动刷新(更新时间,这样避免发布后一直沉在底部). 而且每天的刷新是有限制的,可以定为一个固定值.想一下需要加什么字段
 -联系方式的字段,微信,手机号没有
- 是否审核通过字段(默认自动审核,以后可能对某些简历或二手或兼职进行手工审核) 
- 查看权限 ,可以选择所有人可见 或者仅对自己可见 (参考的赶集网的做法)
