### ISSUE TITLE
Service层完善

### ISSUE THREAD

**Issue by wynfrith** [wynfrith/taolijie#18]
## 记录serivce层还没有实现的功能或要新增的功能

1. 兼职,二手,简历 添加删除收藏的功能 ,以及获取收藏的列表
2. 需要获得用户发布但未审核的二手或兼职列表
3. 用户发布且**已删除**的列表. `用户删除帖子并不是真正的删除,而是伪删除,这里需要变动一下`
4. jobPostService的findJobPost方法如果没有找到id会返回**空指针异常**,最好能返回null

**Comment by wanghongfei** [comment]
删除job的`NotSupportedException`问题在于，你在创建测试数据的时候使用了
```
Arrays.asList(...)
```
方法为集合类对象赋值，这个`asList()`方法返回的`List`对象是不可变的，也就是只能读不能修改，所以我在删除实体的时间会报`NotSupportedException`。
@wynfrith

**Comment by wanghongfei** [comment]
查询未审核的信息方法之前就有了：
```
SHPostService#getUnverifiedPostList()
JobPostService#getUnverifiedPostList()
```
@wynfrith

**Comment by wanghongfei** [comment]
关于空指针，我用了一个更好的实现方法：
如果Service的`findXXX()`方法返回null, 那么就扔`EntityNotExistException`，这是个未检查异常，所以不用`catch`。只要写个异常控制器处理这个异常就行了，不用修改原来的控制器代码 
@wynfrith
