### ISSUE TITLE
坑爹啊，我青轴键盘被浇上牛奶了！！！！

### ISSUE THREAD

**Issue by wanghongfei** [wynfrith/taolijie#5]
都滴到键帽里面去了，电源拔下来了，不知道键盘还能不能用。
现在又用回荼轴的了。。

**Comment by wynfrith** [comment]
卧槽 = = ,机械键盘最怕水了,电路板基本是裸露的...  拔了电反过来放,晾一天再用试试..

在 2015年3月4日 下午9:30，王鸿飞 <notifications@github.com>写道：

**Comment by wanghongfei** [comment]
机械键盘没坏！
